Typescript rewrite
icssc/peterportal-public-api pull request #172
Opened 2022-03-08 17:26 UTC by ramanxg

## Reference Issues
TypeScript Full rewrite

## Summary of Change/Fix 
Rewrites our API into typescript.

## Test Plan

2022-05-02 03:43 UTC, ChaseC99 commented
Sorry still in the process of reviewing this... that's a lot of lines of code 😅 
In the future, I think we should create a feature branch and then do smaller PRs to that. It's much easier to review many small PRs than 1 large PR.

2022-05-02 20:12 UTC, Edwu29 reviewed
Theres more type declarations in /graphql but test plan seems to be working fine

2022-05-02 20:12 UTC, Edwu29 commented on graphql/schema.ts
> +      resolve: async (_, {year, month, day}) => {
I think its helpful to declare the types for the resolve function arguments. Ex. year : str, month : str, day : str

2022-05-02 20:36 UTC, ramanxg commented
> Sorry still in the process of reviewing this... that's a lot of lines of code 😅 
> In the future, I think we should create a feature branch and then do smaller PRs to that. It's much easier to review many small PRs than 1 large PR.

Sorry about that. I actually had that before, but I ended up not reviewing those and instead wanting this one to be reviewed. Will definitely keep that in mind next time.

2022-05-02 20:41 UTC, Edwu29 requested changes

2022-05-02 20:41 UTC, Edwu29 commented on helpers/week.helper.ts
>      date.setDate(date.getDate() + days);
can add type declaration for `yearInput`, `month` and `day` as well

2022-05-02 20:41 UTC, Edwu29 commented on graphql/schema.ts
> +      resolve: (_, {ucinetid}) => {
same here, type strring

2022-05-02 20:41 UTC, Edwu29 commented on graphql/schema.ts
> +      resolve: (_, {id}) => {
and here

2022-05-02 20:41 UTC, Edwu29 commented on graphql/schedule.ts
> +    throw new ValidationError("Must provdide both a year and a quarter.");
small typo here

2022-05-02 20:41 UTC, Edwu29 commented on graphql/schema.ts
> +      resolve: async (_, args) => {
not sure what args type is here.. do we have a type for that? If not can leave it be

2022-05-02 20:41 UTC, Edwu29 commented on graphql/schema.ts
> +        let gradeResults : GradeRawData = undefined;
A little confused with the naming convention here with `GradeRawData` and `GradeDist` and maybe creating a type for `grade_distributions` since that's what we're returning? What I had in mind for the type names was similar to the GraphQL types. Ex. `grade_distributions ` be type `GradeDist`, `grade_results` can stay `GradeRawData` and `agreggate` be `GradeDistAggregate` or `GradeDistAgg`. Thats more intuitive to me, idk I could be wrong

2022-05-02 21:05 UTC, ramanxg commented on graphql/schema.ts
> +      resolve: async (_, {year, month, day}) => {
For destructuring objects in TypeScript, we can't give each variable a type like, `{year : string, month : string, day : string}`. It won't let me do that. I would have to give the entire object a type or interface, but I didn't think that was necessary. Because GraphQL gives it to us as a string, it will have to be a string, so we don't need to enforce the type on our own. 

I can add a type for the week helper method, so that it can be checked there.

2022-05-02 21:06 UTC, ramanxg commented on graphql/schema.ts
> +      resolve: (_, {ucinetid}) => {
See https://github.com/icssc/peterportal-public-api/pull/172#discussion_r863189988

2022-05-02 21:06 UTC, ramanxg commented on graphql/schema.ts
> +      resolve: (_, {id}) => {
See https://github.com/icssc/peterportal-public-api/pull/172#discussion_r863189988

2022-05-02 21:08 UTC, ramanxg commented on graphql/schema.ts
> +      resolve: async (_, args) => {
I think the args object is too variable to need a type, so I didn't add one. We validate it ourselves, and it's provided by GraphQL, so it shouldn't have errors.

2022-05-02 21:27 UTC, ramanxg commented on graphql/schema.ts
> +        let gradeResults : GradeRawData = undefined;
The object type of `grade_distributions` is only used here, so I didn't think to add a type. I'll add one but since it's formatted to be for GraphQL, I think we can use a different name, like `GradeGQLData`. Since it's the `GradeRawData` formatted for GraphQL. 

Thoughts?

2022-05-02 21:34 UTC, ramanxg commented on helpers/week.helper.ts
>      date.setDate(date.getDate() + days);
I think you mean for line 7. If I add the types, I'll get an error looking like this, since query parameters in the url can be multiple types. I considered making this a separate issue, but if we can fix it now that also works. 

![image](https://user-images.githubusercontent.com/9029237/166330872-41b03eb7-f0e9-40af-834e-c8e7f51220bc.png)

2022-05-03 03:01 UTC, Edwu29 commented on graphql/schema.ts
> +        let gradeResults : GradeRawData = undefined;
That sounds like an appropriate name

2022-05-03 03:38 UTC, Edwu29 commented on helpers/week.helper.ts
>      date.setDate(date.getDate() + days);
I found a solution for this. It involves creating a new type and setting the url query to be that type and then passing it into the function getWeek. getWeek can now have type string. If there is a cleaner solution that would be better.
<img width="572" alt="Screen Shot 2022-05-02 at 8 33 55 PM" src="https://user-images.githubusercontent.com/39328613/166401702-cfe17b50-2741-4098-a1b3-d0d370045221.png"> 
<img width="668" alt="Screen Shot 2022-05-02 at 8 35 58 PM" src="https://user-images.githubusercontent.com/39328613/166401819-a04dc02c-1022-4df6-b422-f819f5f56696.png">

2022-05-03 03:39 UTC, Edwu29 commented on helpers/week.helper.ts
>      date.setDate(date.getDate() + days);
Referenced from: https://errorsfixing.com/express-argument-of-type-parsedqs-is-not-assignable-to-parameter-of-type-xxxx/

2022-05-03 18:45 UTC, Edwu29 reviewed
GraphQL files look good!

2022-05-16 06:08 UTC, Edwu29 reviewed
Other than that, looks good. The function queryDatabaseAndResponse looks much better.

2022-05-16 06:08 UTC, Edwu29 commented on helpers/grades.helper.ts
> +export function parseGradesParamsToSQL(query) : WhereParams{
can add typecheck to query, {[key: string]: any}

2022-05-16 06:08 UTC, Edwu29 commented on helpers/grades.helper.ts
> -    return queryDatabase(where.where !== null ? sqlStatement + where.where : sqlStatement).bind(where.params).all().map(result => result.instructor);
i think its better to have the check if where clause is null? not sure

2022-05-16 06:41 UTC, ramanxg commented on helpers/grades.helper.ts
> +export function parseGradesParamsToSQL(query) : WhereParams{
Good catch.

2022-05-16 06:42 UTC, ramanxg commented on helpers/grades.helper.ts
> -    return queryDatabase(where.where !== null ? sqlStatement + where.where : sqlStatement).bind(where.params).all().map(result => result.instructor);
I had it removed, since I didn't think it would ever occur. If you think it's better, I'll add it back.

2022-05-16 06:47 UTC, Edwu29 commented on helpers/grades.helper.ts
> -    return queryDatabase(where.where !== null ? sqlStatement + where.where : sqlStatement).bind(where.params).all().map(result => result.instructor);
I think its better in my opinion because there might be a query with no where clause?

2022-05-16 06:50 UTC, Edwu29 commented
I haven't looked at all the files in detail. Is there a way to get the rewrite in production and revert to the old master if needed? Or if you're confident in it, I'm all for it. I don't think typescript should have much impact on the functionality of the API.

2022-05-16 07:05 UTC, ramanxg commented
> I haven't looked at all the files in detail. Is there a way to get the rewrite in production and revert to the old master if needed? Or if you're confident in it, I'm all for it. I don't think typescript should have much impact on the functionality of the API.

We can always revert to old version through GitHub. Since most of the code logic/functionality wasn't changed I'm pretty confident.

2022-05-16 07:08 UTC, Edwu29 approved these changes

2022-05-16 07:10 UTC, merged