Batch courses & instructors
icssc/peterportal-public-api pull request #207
Opened 2022-05-17 20:12 UTC by Edwu29

## Reference Issues
References #152 but does not close issue. 
## Summary of Change/Fix 
Added an enhancement for batch lookups for courses and instructor information for REST API service. Can now search courses and instructors in batches. using `/courses/all?course=<specify_courses_separated_by_semicolon>` and `/instructors/all?instructor=<specify_instructors_separated_by_semicolon>`. In addition, invalid endpoints are handled. Ex: when specifying a query with an invalid query name, `/courses/all?instructor=mikes`
## Test Plan
`npm test`

#### Courses
http://localhost:8080/rest/v0/courses/all
http://localhost:8080/rest/v0/courses/all?course=I%26CSCI53
http://localhost:8080/rest/v0/courses/all?course=I%26CSCI53;I%26CSCI46
http://localhost:8080/rest/v0/courses/all?course=I%26CSCI53;I%26CSCI46;I%26CSCI32
http://localhost:8080/rest/v0/courses/all?course=mikes (returns {"mikes":null} )

Error
http://localhost:8080/rest/v0/courses/all?instructors=mikes

#### Instructors
http://localhost:8080/rest/v0/instructors/all
http://localhost:8080/rest/v0/instructors/all?instructors=mikes
http://localhost:8080/rest/v0/instructors/all?instructors=mikes;kakagi

Error
http://localhost:8080/rest/v0/instructors/all?course=mikes;kakagi
http://localhost:8080/rest/v0/instructors/all?course=I%26CSCI53

2022-05-17 20:37 UTC, ramanxg requested changes
Nice! It's working well. Just want to add some typing. Also, I think it is better if we keep the response from the all courses function to have the same structure. 

We also need to add documentation for the new feature.

2022-05-17 20:37 UTC, ramanxg commented on helpers/courses.helper.ts
> +}
Can you add type declarations, most importantly for the function argument, and return value.

2022-05-17 20:37 UTC, ramanxg commented on helpers/instructor.helper.ts
> +}
Can you add type declarations, most importantly for the function argument, and return value.

2022-05-17 20:45 UTC, ramanxg commented on rest/v0/courses.ts
> +        res.json(getBatchCourses(req.query.course));
I think we should move the split to the rest endpoint part. If we want to take in an argument in GraphQL, we can pass in a list of strings.

2022-05-19 21:41 UTC, ramanxg reviewed
For the `/courses/{id} endpoint` we can return the same type as whether we have one or multiple. I still want it to be an object. (That's how it will return in GraphQL).

2022-05-19 21:41 UTC, ramanxg commented on rest/v0/courses.ts
> +
Since we aren't using query parameters anymore, we can go back to what it was before. If they add them we can just ignore it.

2022-05-19 21:41 UTC, ramanxg commented on rest/v0/instructor.ts
> +        res.status(404).json(createErrorJSON(404, "Not Found", "Invalid Query"));
Same as course comment

2022-05-24 08:17 UTC, Edwu29 commented on rest/v0/courses.ts
> +
I think it would be better to give invalid message in these cases, but it works either ways.

2022-05-24 19:26 UTC, ramanxg approved these changes

2022-05-24 19:27 UTC, ramanxg commented
Follow up issue, we can add this to the documentation.

2022-05-24 19:27 UTC, merged